###########
# site.title

title:    'Alyson Sherrard'
subtitle: 'UX Designer • Web Developer • Unicorn'
collections:
  content:
    output: true

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
